<?php
defined('BASEPATH') OR exit('No direct script access allowed');

        function provinsi()
        {
                $provinsi = array(
                        'NANGGROE ACEH DARUSSALAM (NAD)' => array(
                                'KAB. ACEH BARAT',
                                'KAB. ACEH BARAT DAYA',
                                'KAB. ACEH BESAR',
                                'KAB. ACEH JAYA',
                                'KAB. ACEH SELATAN',
                                'KAB. ACEH SINGKIL',
                                'KAB. ACEH TAMIANG',
                                'KAB. ACEH TENGAH',
                                'KAB. ACEH TENGGARA',
                                'KAB. ACEH TIMUR',
                                'KAB. ACEH UTARA',
                                'KAB. BENER MERIAH',
                                'KAB. BIREUEN',
                                'KAB. GAYO LUES',
                                'KAB. NAGAN RAYA',
                                'KAB. PIDIE',
                                'KAB. PIDIE JAYA',
                                'KAB. SIMEULUE',
                                'KOTA BANDA ACEH',
                                'KOTA LANGSA',
                                'KOTA LHOKSEUMAWE',
                                'KOTA SABANG',
                                'KOTA SUBULUSSALAM',
                                ),
                        'BALI' => array(
                                'KAB. BADUNG',
                                'KAB. BANGLI',
                                'KAB. BULELENG',
                                'KAB. GIANYAR',
                                'KAB. JEMBRANA',
                                'KAB. KARANGASEM',
                                'KAB. KLUNGKUNG',
                                'KAB. TABANAN',
                                'KOTA DENPASAR',
                                ),
                        'BANGKA BELITUNG' => array(
                                'KAB. BANGKA',
                                'KAB. BANGKA BARAT',
                                'KAB. BANGKA SELATAN',
                                'KAB. BANGKA TENGAH',
                                'KAB. BELITUNG',
                                'KAB. BELITUNG TIMUR',
                                'KOTA PANGKAL PINANG',
                                ),
                        'BANTEN' => array(
                                'KAB. LEBAK',
                                'KAB. PANDEGLANG',
                                'KAB. SERANG',
                                'KAB. TANGERANG',
                                'KOTA CILEGON',
                                'KOTA SERANG',
                                'KOTA TANGERANG',
                                'KOTA TANGERANG SELATAN',
                                ),
                        'BENGKULU' => array(
                                'KAB. BENGKULU SELATAN',
                                'KAB. BENGKULU TENGAH',
                                'KAB. BENGKULU UTARA',
                                'KAB. KAUR',
                                'KAB. KAPAHIANG',
                                'KAB. LEBONG',
                                'KAB. MUKO MUKO',
                                'KAB. REJANG LEBONG',
                                'KAB. SELUMA',
                                'KOTA BENGKULU',
                                ),
                        'DI YOGYAKARTA' => array(
                                'KAB. BANTUL',
                                'KAB. GUNUNG KILDUL',
                                'KAB. KULON PROGO',
                                'KAB. SLEMAN',
                                'KOTA YOGYAKARTA',
                                ),
                        'DKI JAKARTA' => array(
                                'KAB. KEPULAUAN SERIBU',
                                'KOTA JAKARTA BARAT',
                                'KOTA JAKARTA PUSAT',
                                'KOTA JAKARTA SELATAN',
                                'KOTA JAKARTA TIMUR',
                                'KOTA JAKARTA UTARA',
                                ),
                        'GORONTALO' => array(
                                'KAB. BOALEMO',
                                'KAB. BONE BOLANGO',
                                'KAB. GORONTALO',
                                'KAB. GORONTALO UTARA',
                                'KAB. POHUWATO',
                                'KOTA GORONTALO',
                                ),
                        'JAMBI' => array(
                                'KAB. BATANG HARI',
                                'KAB. BUNGO',
                                'KAB. KERINCI',
                                'KAB. MERANGIN',
                                'KAB. MUARO JAMBI',
                                'KAB. SAROLANGUN',
                                'KAB. TANJUNG JABUNG BARAT',
                                'KAB. TANJUNG JABUNG TIMUR',
                                'KAB. TEBO',
                                'KOTA JAMBI',
                                'KOTA SUNGAIPENUH',
                                ),
                        'JAWA BARAT' => array(
                                'KAB. BANDUNG',
                                'KAB. BANDUNG BARAT',
                                'KAB. BEKASI',
                                'KAB. BOGOR',
                                'KAB. CIAMIS',
                                'KAB. CIANJUR',
                                'KAB. CIREBON',
                                'KAB. GARUT',
                                'KAB. INDRAMAYU',
                                'KAB. KARAWANG',
                                'KAB. KUNINGAN',
                                'KAB. MAJALENGKA',
                                'KAB. PANGANDARAN',
                                'KAB. PURWAKARTA',
                                'KAB. SUBANG',
                                'KAB. SUKABUMI',
                                'KAB. SUMEDANG',
                                'KAB. TASIKMALAYA',
                                'KOTA BANDUNG',
                                'KOTA BANJAR',
                                'KOTA BEKASI',
                                'KOTA BOGOR',
                                'KOTA CIMAHI',
                                'KOTA CIREBON',
                                'KOTA DEPOK',
                                'KOTA SUKABUMI',
                                'KOTA TASIKMALAYA',
                                ),
                        'JAWA TENGAH' => array(
                                'KAB. BANJARNEGARA',
                                'KAB. BANYUMAS',
                                'KAB. BATANG',
                                'KAB. BLORA',
                                'KAB. BOYOLALI',
                                'KAB. BREBES',
                                'KAB. CILACAP',
                                'KAB. DEMAK',
                                'KAB. GROBOGAN',
                                'KAB. JEPARA',
                                'KAB. KARANGANYAR',
                                'KAB. KEBUMEN',
                                'KAB. KENDAL',
                                'KAB. KLATEN',
                                'KAB. KUDUS',
                                'KAB. MAGELANG',
                                'KAB. PATI',
                                'KAB. PEKALONGAN',
                                'KAB. PEMALANG',
                                'KAB. PURBALINGGA',
                                'KAB. PURWOREJO',
                                'KAB. REMBANG',
                                'KAB. SEMARANG',
                                'KAB. SRAGEN',
                                'KAB. SUKOHARJO',
                                'KAB. TEGAL',
                                'KAB. TEMANGGUNG',
                                'KAB. WONOGIRI',
                                'KAB. WONOSOBO',
                                'KOTA MAGELANG',
                                'KOTA PEKALONGAN',
                                'KOTA SALATIGA',
                                'KOTA SEMARANG',
                                'KOTA SURAKARTA (SOLO)',
                                'KOTA TEGAL',
                                ),
                        'JAWA TIMUR' => array(
                                'KAB. BANGKALAN',
                                'KAB. BANYUWANGI',
                                'KAB. BLITAR',
                                'KAB. BOJONEGORO',
                                'KAB. BONDOWOSO',
                                'KAB. GRESIK',
                                'KAB. JEMBER',
                                'KAB. JOMBANG',
                                'KAB. KEDIRI',
                                'KAB. LAMONGAN',
                                'KAB. LUMAJANG',
                                'KAB. MADIUN',
                                'KAB. MAGETAN',
                                'KAB. MALANG',
                                'KAB. MOJOKERTO',
                                'KAB. NGANJUK',
                                'KAB. NGAWI',
                                'KAB. PACITAN',
                                'KAB. PAMEKASAN',
                                'KAB. PASURUAN',
                                'KAB. PONOROGO',
                                'KAB. PROBOLINGGO',
                                'KAB. SAMPANG',
                                'KAB. SIDOARJO',
                                'KAB. SITUBONDO',
                                'KAB. SUMENEP',
                                'KAB. TRENGGALEK',
                                'KAB. TUBAN',
                                'KAB. TULUNGAGUNG',
                                'KOTA BATU',
                                'KOTA BLITAR',
                                'KOTA KEDIRI',
                                'KOTA MADIUN',
                                'KOTA MALANG',
                                'KOTA MOJOKERTO',
                                'KOTA PASURUAN',
                                'KOTA PROBOLINGGO',
                                'KOTA SURABAYA',
                                ),
                        'KALIMANTAN BARAT' => array(
                                'KAB. BENGKAYANG',
                                'KAB. KAPUAS HULU',
                                'KAB. KAYONG UTARA',
                                'KAB. KETAPANG',
                                'KAB. KUBU RAYA',
                                'KAB. LANDAK',
                                'KAB. MELAWI',
                                'KAB. PONTIANAK',
                                'KAB. SAMBAS',
                                'KAB. SANGGAU',
                                'KAB. SEKADAU',
                                'KAB. SINTANG',
                                'KOTA PONTIANAK',
                                'KOTA SINGKAWANG',
                                ),
                        'KALIMANTAN SELATAN' => array(
                                'KAB. BALANGAN',
                                'KAB. BANJAR',
                                'KAB. BARITO KUALA',
                                'KAB. HULU SUNGAI SELATAN',
                                'KAB. HULU SUNGAI TENGAH',
                                'KAB. HULU SUNGAI UTARA',
                                'KAB. KOTA BARU',
                                'KAB. TABALONG',
                                'KAB. TANAH BUMBU',
                                'KAB. TANAH LAUT',
                                'KAB. TAPIN',
                                'KOTA BANJARBARU',
                                'KOTA BANJARMASIN',
                                ),
                        'KALIMANTAN TENGAH' => array(
                                'KAB. BARITO SELATAN',
                                'KAB. BARITO TIMUR',
                                'KAB. BARITO UTARA',
                                'KAB. GUNUNG MAS',
                                'KAB. KAPUAS',
                                'KAB. KATINGAN',
                                'KAB. KOTA WARINGIN BARAT',
                                'KAB. KOTA WARINGIN TIMUR',
                                'KAB. LAMANDAU',
                                'KAB. MURUNG RAYA',
                                'KAB. PULANG PISAU',
                                'KAB. SUKAMARA',
                                'KAB. SERUYAN',
                                'KOTA PALANGKA RAYA',
                                ),
                        'KALIMANTAN TIMUR' => array(
                                'KAB. BERAU',
                                'KAB. KUTAI BARAT',
                                'KAB. KUTAI KARTANEGARA',
                                'KAB. KUTAI TIMUR',
                                'KAB. PASER',
                                'KAB. PENAJAM PASER UTARA',
                                'KAB. MAHAKAM ULU',
                                'KOTA BALIKPAPAN',
                                'KOTA BONTANG',
                                'KOTA SAMARINDA',
                                ),
                        'KALIMANTAN UTARA' => array(
                                'KAB. BULUNGAN',
                                'KAB. MALINAU',
                                'KAB. NUNUKAN',
                                'KAB. TANA TIDUNG',
                                'KOTA TARAKAN',
                                ),
                        'KEPULAUAN RIAU' => array(
                                'KAB. BINTAN',
                                'KAB. KARIMUN',
                                'KAB. KEPULAUAN ANAMBAS',
                                'KAB. LINGGA',
                                'KAB. NATUNA',
                                'KOTA BATAM',
                                'KOTA TANJUNG PINANG',
                                ),
                        'LAMPUNG' => array(
                                'KAB. LAMPUNG BARAT',
                                'KAB. LAMPUNG SELATAN',
                                'KAB. LAMPUNG TENGAH',
                                'KAB. LAMPUNG TIMUR',
                                'KAB. LAMPUNG UTARA',
                                'KAB. MESUJI',
                                'KAB. PESAWARAN',
                                'KAB. PRINGSEWU',
                                'KAB. TANGGAMUS',
                                'KAB. TULANG BAWANG',
                                'KAB. TULANG BAWANG BARAT',
                                'KAB. WAY KANAN',
                                'KAB. PESISIR BARAT',
                                'KOTA BANDAR LAMPUNG',
                                'KOTA KOTABUMI',
                                'KOTA LIWA',
                                'KOTA METRO',
                                ),
                        'MALUKU' => array(
                                'KAB. BURU',
                                'KAB. BURU SELATAN',
                                'KAB. KEPULAUAN ARU',
                                'KAB. MALUKU BARAT DAYA',
                                'KAB. MALUKU TENGAH',
                                'KAB. MALUKU TENGGARA',
                                'KAB. MALUKU TENGGARA BARAT',
                                'KAB. SERAM BAGIAN BARAT',
                                'KAB. SERAM BAGIAN TIMUR',
                                'KOTA AMBON',
                                'KOTA TUAL',
                                ),
                        'MALUKU UTARA' => array(
                                'KAB. HALMAHERA BARAT',
                                'KAB. HALMAHERA TENGAH',
                                'KAB. HALMAHERA UTARA',
                                'KAB. HALMAHERA SELATAN',
                                'KAB. HALMAHERA TIMUR',
                                'KAB. KEPULAUAN SULA',
                                'KAB. PULAU MOROTAI',
                                'KAB. PULAU TALIABU',
                                'KOTA TERNATE',
                                'KOTA TIDORE KEPULAUAN',
                                ),
                        'NUSA TENGGARA BARAT (NTB)' => array(
                                'KAB. BIMA',
                                'KAB. DOMPU',
                                'KAB. LOMBOK BARAT',
                                'KAB. LOMBOK TENGAH',
                                'KAB. LOMBOK TIMUR',
                                'KAB. LOMBOK UTARA',
                                'KAB. SUMBAWA',
                                'KAB. SUMBAWA BARAT',
                                'KOTA BIMA',
                                'KOTA MATARAM',
                                ),
                        'NUSA TENGGARA TIMUR (NTT)' => array(
                                'KAB. ALOR',
                                'KAB. BELU',
                                'KAB. ENDE',
                                'KAB. FLORES TIMUR',
                                'KAB. KUPANG',
                                'KAB. LEMBATA',
                                'KAB. MANGGARAI',
                                'KAB. MANGGARAI BARAT',
                                'KAB. MANGGARAI TIMUR',
                                'KAB. NGADA',
                                'KAB. NAGEKEO',
                                'KAB. ROTE NDAO',
                                'KAB. SABU RAIJUA',
                                'KAB. SIKKA',
                                'KAB. SUMBA BARAT',
                                'KAB. SUMBA BARAT DAYA',
                                'KAB. SUMBA TENGAH',
                                'KAB. SUMBA TIMUR',
                                'KAB. TIMOR TENGAH SELATAN',
                                'KAB. TIMOR TENGAH UTARA',
                                'KOTA KUPANG',
                                ),
                        'PAPUA' => array(
                                'KAB. ASMAT',
                                'KAB. BIAK NUMFOR',
                                'KAB. BOVEN DIGOEL',
                                'KAB. DEIYAI',
                                'KAB. DOGIYAI',
                                'KAB. INTAN JAYA',
                                'KAB. JAYAPURA',
                                'KAB. JAYAWIJAYA',
                                'KAB. KEEROM',
                                'KAB. KEPULAUAN YAPEN',
                                'KAB. LANNY JAYA',
                                'KAB. MAMBERAMO RAYA',
                                'KAB. MAMBERAMO TENGAH',
                                'KAB. MAPPI',
                                'KAB. MERAUKE',
                                'KAB. MIMIKA',
                                'KAB. NABIRE',
                                'KAB. NDUGA',
                                'KAB. PANIAI',
                                'KAB. PEGUNUNGAN BINTANG',
                                'KAB. PUNCAK',
                                'KAB. PUNCAK JAYA',
                                'KAB. SARMI',
                                'KAB. SUPIORI',
                                'KAB. TOLIKARA',
                                'KAB. WAROPEN',
                                'KAB. YAHUKIMO',
                                'KAB. YALIMO',
                                'KOTA JAYAPURA',
                                ),
                        'PAPUA BARAT' => array(
                                'KAB. FAKFAK',
                                'KAB. KAIMANA',
                                'KAB. MANOKWARI',
                                'KAB. MANOKWARI SELATAN',
                                'KAB. MAYBRAT',
                                'KAB. PEGUNUNGAN ARFAK',
                                'KAB. RAJA AMPAT',
                                'KAB. SORONG',
                                'KAB. SORONG SELATAN',
                                'KAB. TAMBRAUW',
                                'KAB. TELUK BINTUNI',
                                'KAB. TELUK WONDAMA',
                                'KOTA SORONG',
                                ),
                        'RIAU' => array(
                                'KAB. BENGKALIS',
                                'KAB. INDRAGIRI HILIR',
                                'KAB. INDRAGIRI HULU',
                                'KAB. KAMPAR',
                                'KAB. KUANTAN SINGINGI',
                                'KAB. PELALAWAN',
                                'KAB. ROKAN HILIR',
                                'KAB. ROKAN HULU',
                                'KAB. SIAK',
                                'KAB. KEPULAUAN MERANTI',
                                'KOTA DUMAI',
                                'KOTA PEKANBARU',
                                ),
                        'SULAWESI BARAT' => array(
                                'KAB. MAJENE',
                                'KAB. MAMASA',
                                'KAB. MAMUJU',
                                'KAB. MAMUJU UTARA',
                                'KAB. POLEWALI MANDAR',
                                'KAB. MAMUJU TENGAH',
                                ),
                        'SULAWESI SELATAN' => array(
                                'KAB. BANTAENG',
                                'KAB. BARRU',
                                'KAB. BONE WATAMPONE',
                                'KAB. BULUKUMBA',
                                'KAB. ENREKANG',
                                'KAB. GOWA',
                                'KAB. JENEPONTO',
                                'KAB. KEPULAUAN SELAYAR',
                                'KAB. LUWU',
                                'KAB. LUWU TIMUR',
                                'KAB. LUWU UTARA',
                                'KAB. MAROS',
                                'KAB. PANGKAJENE DAN KEPULAUAN',
                                'KAB. SELAYAR (KEPULAUAN SELAYAR)',
                                'KAB. PINRANG',
                                'KAB. SIDENRENG RAPPANG/RAPANG',
                                'KAB. SINJAI',
                                'KAB. SOPPENG',
                                'KAB. TAKALAR',
                                'KAB. TANA TORAJA',
                                'KAB. TORAJA UTARA',
                                'KAB. WAJO',
                                'KOTA MAKASSAR',
                                'KOTA PALOPO',
                                'KOTA PAREPARE',
                                ),
                        'SULAWESI TENGAH' => array(
                                'KAB. BANGGAI',
                                'KAB. BANGGAI KEPULAUAN',
                                'KAB. BANGGAI LAUT',
                                'KAB. BUOL',
                                'KAB. DONGGALA',
                                'KAB. MOROWALI',
                                'KAB. PARIGI MOUTONG',
                                'KAB. POSO',
                                'KAB. SIGI',
                                'KAB. TOJO UNA-UNA',
                                'KAB. TOLITOLI',
                                'KOTA PALU',
                                ),
                        'SULAWESI TENGGARA' => array(
                                'KAB. BOMBANA',
                                'KAB. BUTON',
                                'KAB. BUTON UTARA',
                                'KAB. KOLAKA',
                                'KAB. KOLAKA TIMUR',
                                'KAB. KOLAKA UTARA',
                                'KAB. KONAWE',
                                'KAB. KONAWE SELATAN',
                                'KAB. KONAWE UTARA',
                                'KAB. KONAWE KEPULAUAN',
                                'KAB. MUNA',
                                'KAB. WAKATOBI',
                                'KOTA BAU-BAU',
                                'KOTA KENDARI',
                                ),
                        'SULAWESI UTARA' => array(
                                'KAB. BOLAANG MONGONDOW',
                                'KAB. BOLAANG MONGONDOW SELATAN',
                                'KAB. BOLAANG MONGONDOW TIMUR',
                                'KAB. BOLAANG MONGONDOW UTARA',
                                'KAB. KEPULAUAN SANGIHE',
                                'KAB. KEPULAUAN SIAU TAGULANDANG BIARO',
                                'KAB. KEPULAUAN TALAUD',
                                'KAB. MINAHASA',
                                'KAB. MINAHASA SELATAN',
                                'KAB. MINAHASA TENGGARA',
                                'KAB. MINAHASA UTARA',
                                'KOTA BITUNG',
                                'KOTA KOTAMOBAGU',
                                'KOTA MANADO',
                                'KOTA TOMOHON',
                                ),
                        'SUMATERA BARAT' => array(
                                'KAB. AGAM',
                                'KAB. DHARMASRAYA',
                                'KAB. KEPULAUAN MENTAWAI',
                                'KAB. LIMA PULUH KOTO/KOTA',
                                'KAB. PADANG PARIAMAN',
                                'KAB. PASAMAN',
                                'KAB. PASAMAN BARAT',
                                'KAB. PESISIR SELATAN',
                                'KAB. SIJUNJUNG',
                                'KAB. SOLOK',
                                'KAB. SOLOK SELATAN',
                                'KAB. TANAH DATAR',
                                'KOTA BUKITTINGGI',
                                'KOTA PADANG',
                                'KOTA PADANG PANJANG',
                                'KOTA PARIAMAN',
                                'KOTA PAYAKUMBUH',
                                'KOTA SAWAH LUNTO',
                                'KOTA SOLOK',
                                ),
                        'SUMATERA SELATAN' => array(
                                'KAB. BANYUASIN',
                                'KAB. EMPAT LAWANG',
                                'KAB. LAHAT',
                                'KAB. MUARA ENIM',
                                'KAB. MUSI BANYUASIN',
                                'KAB. MUSI RAWAS',
                                'KAB. OGAN ILIR',
                                'KAB. OGAN KOMERING ILIR',
                                'KAB. OGAN KOMERING ULU',
                                'KAB. OGAN KOMERING ULU SELATAN',
                                'KAB. PENUKAL ABAB LEMATANG ILIR',
                                'KAB. OGAN KOMERING ULU TIMUR',
                                'KOTA LUBUK LINGGAU',
                                'KOTA PAGAR ALAM',
                                'KOTA PALEMBANG',
                                'KOTA PRABUMULIH',
                                ),
                        'SUMATERA UTARA' => array(
                                'KAB. ASAHAN',
                                'KAB. BATUBARA',
                                'KAB. DAIRI',
                                'KAB. DELI SERDANG',
                                'KAB. HUMBANG HASUNDUTAN',
                                'KAB. KARO',
                                'KAB. KARO KABANJAHE',
                                'KAB. LABUHAN BATU',
                                'KAB. LABUHAN BATU SELATAN',
                                'KAB. LABUHAN BATU UTARA',
                                'KAB. LANGKAT',
                                'KAB. MANDAILING NATAL',
                                'KAB. NIAS',
                                'KAB. NIAS BARAT',
                                'KAB. NIAS SELATAN',
                                'KAB. NIAS UTARA',
                                'KAB. PADANG LAWAS',
                                'KAB. PADANG LAWAS UTARA',
                                'KAB. PAKPAK BHARAT',
                                'KAB. SAMOSIR',
                                'KAB. SERDANG BEDAGAI',
                                'KAB. SIMALUNGUN',
                                'KAB. TAPANULI SELATAN',
                                'KAB. TAPANULI TENGAH',
                                'KAB. TAPANULI UTARA',
                                'KAB. TOBA SAMOSIR',
                                'KOTA BINJAI',
                                'KOTA GUNUNGSITOLI',
                                'KOTA MEDAN',
                                'KOTA PADANG SIDEMPUAN',
                                'KOTA PEMATANG SIANTAR',
                                'KOTA SIBOLGA',
                                'KOTA TANJUNG BALAI',
                                'KOTA TEBING TINGGI',
                                ),
                        );

                foreach ($provinsi as $indeks => $value) {
                        $result['']      = '- Pilih Provinsi -';       
                        $result[$indeks] = $indeks;
                }
                return $result;
        }

        function kabupaten_indeks($value)
        {
                $kabupaten = array(
                        'NANGGROE ACEH DARUSSALAM (NAD)' => array(
                                'KAB. ACEH BARAT',
                                'KAB. ACEH BARAT DAYA',
                                'KAB. ACEH BESAR',
                                'KAB. ACEH JAYA',
                                'KAB. ACEH SELATAN',
                                'KAB. ACEH SINGKIL',
                                'KAB. ACEH TAMIANG',
                                'KAB. ACEH TENGAH',
                                'KAB. ACEH TENGGARA',
                                'KAB. ACEH TIMUR',
                                'KAB. ACEH UTARA',
                                'KAB. BENER MERIAH',
                                'KAB. BIREUEN',
                                'KAB. GAYO LUES',
                                'KAB. NAGAN RAYA',
                                'KAB. PIDIE',
                                'KAB. PIDIE JAYA',
                                'KAB. SIMEULUE',
                                'KOTA BANDA ACEH',
                                'KOTA LANGSA',
                                'KOTA LHOKSEUMAWE',
                                'KOTA SABANG',
                                'KOTA SUBULUSSALAM',
                                ),
                        'BALI' => array(
                                'KAB. BADUNG',
                                'KAB. BANGLI',
                                'KAB. BULELENG',
                                'KAB. GIANYAR',
                                'KAB. JEMBRANA',
                                'KAB. KARANGASEM',
                                'KAB. KLUNGKUNG',
                                'KAB. TABANAN',
                                'KOTA DENPASAR',
                                ),
                        'BANGKA BELITUNG' => array(
                                'KAB. BANGKA',
                                'KAB. BANGKA BARAT',
                                'KAB. BANGKA SELATAN',
                                'KAB. BANGKA TENGAH',
                                'KAB. BELITUNG',
                                'KAB. BELITUNG TIMUR',
                                'KOTA PANGKAL PINANG',
                                ),
                        'BANTEN' => array(
                                'KAB. LEBAK',
                                'KAB. PANDEGLANG',
                                'KAB. SERANG',
                                'KAB. TANGERANG',
                                'KOTA CILEGON',
                                'KOTA SERANG',
                                'KOTA TANGERANG',
                                'KOTA TANGERANG SELATAN',
                                ),
                        'BENGKULU' => array(
                                'KAB. BENGKULU SELATAN',
                                'KAB. BENGKULU TENGAH',
                                'KAB. BENGKULU UTARA',
                                'KAB. KAUR',
                                'KAB. KAPAHIANG',
                                'KAB. LEBONG',
                                'KAB. MUKO MUKO',
                                'KAB. REJANG LEBONG',
                                'KAB. SELUMA',
                                'KOTA BENGKULU',
                                ),
                        'DI YOGYAKARTA' => array(
                                'KAB. BANTUL',
                                'KAB. GUNUNG KILDUL',
                                'KAB. KULON PROGO',
                                'KAB. SLEMAN',
                                'KOTA YOGYAKARTA',
                                ),
                        'DKI JAKARTA' => array(
                                'KAB. KEPULAUAN SERIBU',
                                'KOTA JAKARTA BARAT',
                                'KOTA JAKARTA PUSAT',
                                'KOTA JAKARTA SELATAN',
                                'KOTA JAKARTA TIMUR',
                                'KOTA JAKARTA UTARA',
                                ),
                        'GORONTALO' => array(
                                'KAB. BOALEMO',
                                'KAB. BONE BOLANGO',
                                'KAB. GORONTALO',
                                'KAB. GORONTALO UTARA',
                                'KAB. POHUWATO',
                                'KOTA GORONTALO',
                                ),
                        'JAMBI' => array(
                                'KAB. BATANG HARI',
                                'KAB. BUNGO',
                                'KAB. KERINCI',
                                'KAB. MERANGIN',
                                'KAB. MUARO JAMBI',
                                'KAB. SAROLANGUN',
                                'KAB. TANJUNG JABUNG BARAT',
                                'KAB. TANJUNG JABUNG TIMUR',
                                'KAB. TEBO',
                                'KOTA JAMBI',
                                'KOTA SUNGAIPENUH',
                                ),
                        'JAWA BARAT' => array(
                                'KAB. BANDUNG',
                                'KAB. BANDUNG BARAT',
                                'KAB. BEKASI',
                                'KAB. BOGOR',
                                'KAB. CIAMIS',
                                'KAB. CIANJUR',
                                'KAB. CIREBON',
                                'KAB. GARUT',
                                'KAB. INDRAMAYU',
                                'KAB. KARAWANG',
                                'KAB. KUNINGAN',
                                'KAB. MAJALENGKA',
                                'KAB. PANGANDARAN',
                                'KAB. PURWAKARTA',
                                'KAB. SUBANG',
                                'KAB. SUKABUMI',
                                'KAB. SUMEDANG',
                                'KAB. TASIKMALAYA',
                                'KOTA BANDUNG',
                                'KOTA BANJAR',
                                'KOTA BEKASI',
                                'KOTA BOGOR',
                                'KOTA CIMAHI',
                                'KOTA CIREBON',
                                'KOTA DEPOK',
                                'KOTA SUKABUMI',
                                'KOTA TASIKMALAYA',
                                ),
                        'JAWA TENGAH' => array(
                                'KAB. BANJARNEGARA',
                                'KAB. BANYUMAS',
                                'KAB. BATANG',
                                'KAB. BLORA',
                                'KAB. BOYOLALI',
                                'KAB. BREBES',
                                'KAB. CILACAP',
                                'KAB. DEMAK',
                                'KAB. GROBOGAN',
                                'KAB. JEPARA',
                                'KAB. KARANGANYAR',
                                'KAB. KEBUMEN',
                                'KAB. KENDAL',
                                'KAB. KLATEN',
                                'KAB. KUDUS',
                                'KAB. MAGELANG',
                                'KAB. PATI',
                                'KAB. PEKALONGAN',
                                'KAB. PEMALANG',
                                'KAB. PURBALINGGA',
                                'KAB. PURWOREJO',
                                'KAB. REMBANG',
                                'KAB. SEMARANG',
                                'KAB. SRAGEN',
                                'KAB. SUKOHARJO',
                                'KAB. TEGAL',
                                'KAB. TEMANGGUNG',
                                'KAB. WONOGIRI',
                                'KAB. WONOSOBO',
                                'KOTA MAGELANG',
                                'KOTA PEKALONGAN',
                                'KOTA SALATIGA',
                                'KOTA SEMARANG',
                                'KOTA SURAKARTA (SOLO)',
                                'KOTA TEGAL',
                                ),
                        'JAWA TIMUR' => array(
                                'KAB. BANGKALAN',
                                'KAB. BANYUWANGI',
                                'KAB. BLITAR',
                                'KAB. BOJONEGORO',
                                'KAB. BONDOWOSO',
                                'KAB. GRESIK',
                                'KAB. JEMBER',
                                'KAB. JOMBANG',
                                'KAB. KEDIRI',
                                'KAB. LAMONGAN',
                                'KAB. LUMAJANG',
                                'KAB. MADIUN',
                                'KAB. MAGETAN',
                                'KAB. MALANG',
                                'KAB. MOJOKERTO',
                                'KAB. NGANJUK',
                                'KAB. NGAWI',
                                'KAB. PACITAN',
                                'KAB. PAMEKASAN',
                                'KAB. PASURUAN',
                                'KAB. PONOROGO',
                                'KAB. PROBOLINGGO',
                                'KAB. SAMPANG',
                                'KAB. SIDOARJO',
                                'KAB. SITUBONDO',
                                'KAB. SUMENEP',
                                'KAB. TRENGGALEK',
                                'KAB. TUBAN',
                                'KAB. TULUNGAGUNG',
                                'KOTA BATU',
                                'KOTA BLITAR',
                                'KOTA KEDIRI',
                                'KOTA MADIUN',
                                'KOTA MALANG',
                                'KOTA MOJOKERTO',
                                'KOTA PASURUAN',
                                'KOTA PROBOLINGGO',
                                'KOTA SURABAYA',
                                ),
                        'KALIMANTAN BARAT' => array(
                                'KAB. BENGKAYANG',
                                'KAB. KAPUAS HULU',
                                'KAB. KAYONG UTARA',
                                'KAB. KETAPANG',
                                'KAB. KUBU RAYA',
                                'KAB. LANDAK',
                                'KAB. MELAWI',
                                'KAB. PONTIANAK',
                                'KAB. SAMBAS',
                                'KAB. SANGGAU',
                                'KAB. SEKADAU',
                                'KAB. SINTANG',
                                'KOTA PONTIANAK',
                                'KOTA SINGKAWANG',
                                ),
                        'KALIMANTAN SELATAN' => array(
                                'KAB. BALANGAN',
                                'KAB. BANJAR',
                                'KAB. BARITO KUALA',
                                'KAB. HULU SUNGAI SELATAN',
                                'KAB. HULU SUNGAI TENGAH',
                                'KAB. HULU SUNGAI UTARA',
                                'KAB. KOTA BARU',
                                'KAB. TABALONG',
                                'KAB. TANAH BUMBU',
                                'KAB. TANAH LAUT',
                                'KAB. TAPIN',
                                'KOTA BANJARBARU',
                                'KOTA BANJARMASIN',
                                ),
                        'KALIMANTAN TENGAH' => array(
                                'KAB. BARITO SELATAN',
                                'KAB. BARITO TIMUR',
                                'KAB. BARITO UTARA',
                                'KAB. GUNUNG MAS',
                                'KAB. KAPUAS',
                                'KAB. KATINGAN',
                                'KAB. KOTA WARINGIN BARAT',
                                'KAB. KOTA WARINGIN TIMUR',
                                'KAB. LAMANDAU',
                                'KAB. MURUNG RAYA',
                                'KAB. PULANG PISAU',
                                'KAB. SUKAMARA',
                                'KAB. SERUYAN',
                                'KOTA PALANGKA RAYA',
                                ),
                        'KALIMANTAN TIMUR' => array(
                                'KAB. BERAU',
                                'KAB. KUTAI BARAT',
                                'KAB. KUTAI KARTANEGARA',
                                'KAB. KUTAI TIMUR',
                                'KAB. PASER',
                                'KAB. PENAJAM PASER UTARA',
                                'KAB. MAHAKAM ULU',
                                'KOTA BALIKPAPAN',
                                'KOTA BONTANG',
                                'KOTA SAMARINDA',
                                ),
                        'KALIMANTAN UTARA' => array(
                                'KAB. BULUNGAN',
                                'KAB. MALINAU',
                                'KAB. NUNUKAN',
                                'KAB. TANA TIDUNG',
                                'KOTA TARAKAN',
                                ),
                        'KEPULAUAN RIAU' => array(
                                'KAB. BINTAN',
                                'KAB. KARIMUN',
                                'KAB. KEPULAUAN ANAMBAS',
                                'KAB. LINGGA',
                                'KAB. NATUNA',
                                'KOTA BATAM',
                                'KOTA TANJUNG PINANG',
                                ),
                        'LAMPUNG' => array(
                                'KAB. LAMPUNG BARAT',
                                'KAB. LAMPUNG SELATAN',
                                'KAB. LAMPUNG TENGAH',
                                'KAB. LAMPUNG TIMUR',
                                'KAB. LAMPUNG UTARA',
                                'KAB. MESUJI',
                                'KAB. PESAWARAN',
                                'KAB. PRINGSEWU',
                                'KAB. TANGGAMUS',
                                'KAB. TULANG BAWANG',
                                'KAB. TULANG BAWANG BARAT',
                                'KAB. WAY KANAN',
                                'KAB. PESISIR BARAT',
                                'KOTA BANDAR LAMPUNG',
                                'KOTA KOTABUMI',
                                'KOTA LIWA',
                                'KOTA METRO',
                                ),
                        'MALUKU' => array(
                                'KAB. BURU',
                                'KAB. BURU SELATAN',
                                'KAB. KEPULAUAN ARU',
                                'KAB. MALUKU BARAT DAYA',
                                'KAB. MALUKU TENGAH',
                                'KAB. MALUKU TENGGARA',
                                'KAB. MALUKU TENGGARA BARAT',
                                'KAB. SERAM BAGIAN BARAT',
                                'KAB. SERAM BAGIAN TIMUR',
                                'KOTA AMBON',
                                'KOTA TUAL',
                                ),
                        'MALUKU UTARA' => array(
                                'KAB. HALMAHERA BARAT',
                                'KAB. HALMAHERA TENGAH',
                                'KAB. HALMAHERA UTARA',
                                'KAB. HALMAHERA SELATAN',
                                'KAB. HALMAHERA TIMUR',
                                'KAB. KEPULAUAN SULA',
                                'KAB. PULAU MOROTAI',
                                'KAB. PULAU TALIABU',
                                'KOTA TERNATE',
                                'KOTA TIDORE KEPULAUAN',
                                ),
                        'NUSA TENGGARA BARAT (NTB)' => array(
                                'KAB. BIMA',
                                'KAB. DOMPU',
                                'KAB. LOMBOK BARAT',
                                'KAB. LOMBOK TENGAH',
                                'KAB. LOMBOK TIMUR',
                                'KAB. LOMBOK UTARA',
                                'KAB. SUMBAWA',
                                'KAB. SUMBAWA BARAT',
                                'KOTA BIMA',
                                'KOTA MATARAM',
                                ),
                        'NUSA TENGGARA TIMUR (NTT)' => array(
                                'KAB. ALOR',
                                'KAB. BELU',
                                'KAB. ENDE',
                                'KAB. FLORES TIMUR',
                                'KAB. KUPANG',
                                'KAB. LEMBATA',
                                'KAB. MANGGARAI',
                                'KAB. MANGGARAI BARAT',
                                'KAB. MANGGARAI TIMUR',
                                'KAB. NGADA',
                                'KAB. NAGEKEO',
                                'KAB. ROTE NDAO',
                                'KAB. SABU RAIJUA',
                                'KAB. SIKKA',
                                'KAB. SUMBA BARAT',
                                'KAB. SUMBA BARAT DAYA',
                                'KAB. SUMBA TENGAH',
                                'KAB. SUMBA TIMUR',
                                'KAB. TIMOR TENGAH SELATAN',
                                'KAB. TIMOR TENGAH UTARA',
                                'KOTA KUPANG',
                                ),
                        'PAPUA' => array(
                                'KAB. ASMAT',
                                'KAB. BIAK NUMFOR',
                                'KAB. BOVEN DIGOEL',
                                'KAB. DEIYAI',
                                'KAB. DOGIYAI',
                                'KAB. INTAN JAYA',
                                'KAB. JAYAPURA',
                                'KAB. JAYAWIJAYA',
                                'KAB. KEEROM',
                                'KAB. KEPULAUAN YAPEN',
                                'KAB. LANNY JAYA',
                                'KAB. MAMBERAMO RAYA',
                                'KAB. MAMBERAMO TENGAH',
                                'KAB. MAPPI',
                                'KAB. MERAUKE',
                                'KAB. MIMIKA',
                                'KAB. NABIRE',
                                'KAB. NDUGA',
                                'KAB. PANIAI',
                                'KAB. PEGUNUNGAN BINTANG',
                                'KAB. PUNCAK',
                                'KAB. PUNCAK JAYA',
                                'KAB. SARMI',
                                'KAB. SUPIORI',
                                'KAB. TOLIKARA',
                                'KAB. WAROPEN',
                                'KAB. YAHUKIMO',
                                'KAB. YALIMO',
                                'KOTA JAYAPURA',
                                ),
                        'PAPUA BARAT' => array(
                                'KAB. FAKFAK',
                                'KAB. KAIMANA',
                                'KAB. MANOKWARI',
                                'KAB. MANOKWARI SELATAN',
                                'KAB. MAYBRAT',
                                'KAB. PEGUNUNGAN ARFAK',
                                'KAB. RAJA AMPAT',
                                'KAB. SORONG',
                                'KAB. SORONG SELATAN',
                                'KAB. TAMBRAUW',
                                'KAB. TELUK BINTUNI',
                                'KAB. TELUK WONDAMA',
                                'KOTA SORONG',
                                ),
                        'RIAU' => array(
                                'KAB. BENGKALIS',
                                'KAB. INDRAGIRI HILIR',
                                'KAB. INDRAGIRI HULU',
                                'KAB. KAMPAR',
                                'KAB. KUANTAN SINGINGI',
                                'KAB. PELALAWAN',
                                'KAB. ROKAN HILIR',
                                'KAB. ROKAN HULU',
                                'KAB. SIAK',
                                'KAB. KEPULAUAN MERANTI',
                                'KOTA DUMAI',
                                'KOTA PEKANBARU',
                                ),
                        'SULAWESI BARAT' => array(
                                'KAB. MAJENE',
                                'KAB. MAMASA',
                                'KAB. MAMUJU',
                                'KAB. MAMUJU UTARA',
                                'KAB. POLEWALI MANDAR',
                                'KAB. MAMUJU TENGAH',
                                ),
                        'SULAWESI SELATAN' => array(
                                'KAB. BANTAENG',
                                'KAB. BARRU',
                                'KAB. BONE WATAMPONE',
                                'KAB. BULUKUMBA',
                                'KAB. ENREKANG',
                                'KAB. GOWA',
                                'KAB. JENEPONTO',
                                'KAB. KEPULAUAN SELAYAR',
                                'KAB. LUWU',
                                'KAB. LUWU TIMUR',
                                'KAB. LUWU UTARA',
                                'KAB. MAROS',
                                'KAB. PANGKAJENE DAN KEPULAUAN',
                                'KAB. SELAYAR (KEPULAUAN SELAYAR)',
                                'KAB. PINRANG',
                                'KAB. SIDENRENG RAPPANG/RAPANG',
                                'KAB. SINJAI',
                                'KAB. SOPPENG',
                                'KAB. TAKALAR',
                                'KAB. TANA TORAJA',
                                'KAB. TORAJA UTARA',
                                'KAB. WAJO',
                                'KOTA MAKASSAR',
                                'KOTA PALOPO',
                                'KOTA PAREPARE',
                                ),
                        'SULAWESI TENGAH' => array(
                                'KAB. BANGGAI',
                                'KAB. BANGGAI KEPULAUAN',
                                'KAB. BANGGAI LAUT',
                                'KAB. BUOL',
                                'KAB. DONGGALA',
                                'KAB. MOROWALI',
                                'KAB. PARIGI MOUTONG',
                                'KAB. POSO',
                                'KAB. SIGI',
                                'KAB. TOJO UNA-UNA',
                                'KAB. TOLITOLI',
                                'KOTA PALU',
                                ),
                        'SULAWESI TENGGARA' => array(
                                'KAB. BOMBANA',
                                'KAB. BUTON',
                                'KAB. BUTON UTARA',
                                'KAB. KOLAKA',
                                'KAB. KOLAKA TIMUR',
                                'KAB. KOLAKA UTARA',
                                'KAB. KONAWE',
                                'KAB. KONAWE SELATAN',
                                'KAB. KONAWE UTARA',
                                'KAB. KONAWE KEPULAUAN',
                                'KAB. MUNA',
                                'KAB. WAKATOBI',
                                'KOTA BAU-BAU',
                                'KOTA KENDARI',
                                ),
                        'SULAWESI UTARA' => array(
                                'KAB. BOLAANG MONGONDOW',
                                'KAB. BOLAANG MONGONDOW SELATAN',
                                'KAB. BOLAANG MONGONDOW TIMUR',
                                'KAB. BOLAANG MONGONDOW UTARA',
                                'KAB. KEPULAUAN SANGIHE',
                                'KAB. KEPULAUAN SIAU TAGULANDANG BIARO',
                                'KAB. KEPULAUAN TALAUD',
                                'KAB. MINAHASA',
                                'KAB. MINAHASA SELATAN',
                                'KAB. MINAHASA TENGGARA',
                                'KAB. MINAHASA UTARA',
                                'KOTA BITUNG',
                                'KOTA KOTAMOBAGU',
                                'KOTA MANADO',
                                'KOTA TOMOHON',
                                ),
                        'SUMATERA BARAT' => array(
                                'KAB. AGAM',
                                'KAB. DHARMASRAYA',
                                'KAB. KEPULAUAN MENTAWAI',
                                'KAB. LIMA PULUH KOTO/KOTA',
                                'KAB. PADANG PARIAMAN',
                                'KAB. PASAMAN',
                                'KAB. PASAMAN BARAT',
                                'KAB. PESISIR SELATAN',
                                'KAB. SIJUNJUNG',
                                'KAB. SOLOK',
                                'KAB. SOLOK SELATAN',
                                'KAB. TANAH DATAR',
                                'KOTA BUKITTINGGI',
                                'KOTA PADANG',
                                'KOTA PADANG PANJANG',
                                'KOTA PARIAMAN',
                                'KOTA PAYAKUMBUH',
                                'KOTA SAWAH LUNTO',
                                'KOTA SOLOK',
                                ),
                        'SUMATERA SELATAN' => array(
                                'KAB. BANYUASIN',
                                'KAB. EMPAT LAWANG',
                                'KAB. LAHAT',
                                'KAB. MUARA ENIM',
                                'KAB. MUSI BANYUASIN',
                                'KAB. MUSI RAWAS',
                                'KAB. OGAN ILIR',
                                'KAB. OGAN KOMERING ILIR',
                                'KAB. OGAN KOMERING ULU',
                                'KAB. OGAN KOMERING ULU SELATAN',
                                'KAB. PENUKAL ABAB LEMATANG ILIR',
                                'KAB. OGAN KOMERING ULU TIMUR',
                                'KOTA LUBUK LINGGAU',
                                'KOTA PAGAR ALAM',
                                'KOTA PALEMBANG',
                                'KOTA PRABUMULIH',
                                ),
                        'SUMATERA UTARA' => array(
                                'KAB. ASAHAN',
                                'KAB. BATUBARA',
                                'KAB. DAIRI',
                                'KAB. DELI SERDANG',
                                'KAB. HUMBANG HASUNDUTAN',
                                'KAB. KARO',
                                'KAB. KARO KABANJAHE',
                                'KAB. LABUHAN BATU',
                                'KAB. LABUHAN BATU SELATAN',
                                'KAB. LABUHAN BATU UTARA',
                                'KAB. LANGKAT',
                                'KAB. MANDAILING NATAL',
                                'KAB. NIAS',
                                'KAB. NIAS BARAT',
                                'KAB. NIAS SELATAN',
                                'KAB. NIAS UTARA',
                                'KAB. PADANG LAWAS',
                                'KAB. PADANG LAWAS UTARA',
                                'KAB. PAKPAK BHARAT',
                                'KAB. SAMOSIR',
                                'KAB. SERDANG BEDAGAI',
                                'KAB. SIMALUNGUN',
                                'KAB. TAPANULI SELATAN',
                                'KAB. TAPANULI TENGAH',
                                'KAB. TAPANULI UTARA',
                                'KAB. TOBA SAMOSIR',
                                'KOTA BINJAI',
                                'KOTA GUNUNGSITOLI',
                                'KOTA MEDAN',
                                'KOTA PADANG SIDEMPUAN',
                                'KOTA PEMATANG SIANTAR',
                                'KOTA SIBOLGA',
                                'KOTA TANJUNG BALAI',
                                'KOTA TEBING TINGGI',
                                ),
                        );
                
                foreach ($kabupaten[$value] as $indeks) {
                        $result['']      = '- Pilih Kabupaten -';       
                        $result[$indeks] = $indeks;
                }
                return $result;

                // return $kabupaten[$value];
        }

        function kabupaten($value)
        {
                $kabupaten = array(
                        'NANGGROE ACEH DARUSSALAM (NAD)' => array(
                                'KAB. ACEH BARAT',
                                'KAB. ACEH BARAT DAYA',
                                'KAB. ACEH BESAR',
                                'KAB. ACEH JAYA',
                                'KAB. ACEH SELATAN',
                                'KAB. ACEH SINGKIL',
                                'KAB. ACEH TAMIANG',
                                'KAB. ACEH TENGAH',
                                'KAB. ACEH TENGGARA',
                                'KAB. ACEH TIMUR',
                                'KAB. ACEH UTARA',
                                'KAB. BENER MERIAH',
                                'KAB. BIREUEN',
                                'KAB. GAYO LUES',
                                'KAB. NAGAN RAYA',
                                'KAB. PIDIE',
                                'KAB. PIDIE JAYA',
                                'KAB. SIMEULUE',
                                'KOTA BANDA ACEH',
                                'KOTA LANGSA',
                                'KOTA LHOKSEUMAWE',
                                'KOTA SABANG',
                                'KOTA SUBULUSSALAM',
                                ),
                        'BALI' => array(
                                'KAB. BADUNG',
                                'KAB. BANGLI',
                                'KAB. BULELENG',
                                'KAB. GIANYAR',
                                'KAB. JEMBRANA',
                                'KAB. KARANGASEM',
                                'KAB. KLUNGKUNG',
                                'KAB. TABANAN',
                                'KOTA DENPASAR',
                                ),
                        'BANGKA BELITUNG' => array(
                                'KAB. BANGKA',
                                'KAB. BANGKA BARAT',
                                'KAB. BANGKA SELATAN',
                                'KAB. BANGKA TENGAH',
                                'KAB. BELITUNG',
                                'KAB. BELITUNG TIMUR',
                                'KOTA PANGKAL PINANG',
                                ),
                        'BANTEN' => array(
                                'KAB. LEBAK',
                                'KAB. PANDEGLANG',
                                'KAB. SERANG',
                                'KAB. TANGERANG',
                                'KOTA CILEGON',
                                'KOTA SERANG',
                                'KOTA TANGERANG',
                                'KOTA TANGERANG SELATAN',
                                ),
                        'BENGKULU' => array(
                                'KAB. BENGKULU SELATAN',
                                'KAB. BENGKULU TENGAH',
                                'KAB. BENGKULU UTARA',
                                'KAB. KAUR',
                                'KAB. KAPAHIANG',
                                'KAB. LEBONG',
                                'KAB. MUKO MUKO',
                                'KAB. REJANG LEBONG',
                                'KAB. SELUMA',
                                'KOTA BENGKULU',
                                ),
                        'DI YOGYAKARTA' => array(
                                'KAB. BANTUL',
                                'KAB. GUNUNG KILDUL',
                                'KAB. KULON PROGO',
                                'KAB. SLEMAN',
                                'KOTA YOGYAKARTA',
                                ),
                        'DKI JAKARTA' => array(
                                'KAB. KEPULAUAN SERIBU',
                                'KOTA JAKARTA BARAT',
                                'KOTA JAKARTA PUSAT',
                                'KOTA JAKARTA SELATAN',
                                'KOTA JAKARTA TIMUR',
                                'KOTA JAKARTA UTARA',
                                ),
                        'GORONTALO' => array(
                                'KAB. BOALEMO',
                                'KAB. BONE BOLANGO',
                                'KAB. GORONTALO',
                                'KAB. GORONTALO UTARA',
                                'KAB. POHUWATO',
                                'KOTA GORONTALO',
                                ),
                        'JAMBI' => array(
                                'KAB. BATANG HARI',
                                'KAB. BUNGO',
                                'KAB. KERINCI',
                                'KAB. MERANGIN',
                                'KAB. MUARO JAMBI',
                                'KAB. SAROLANGUN',
                                'KAB. TANJUNG JABUNG BARAT',
                                'KAB. TANJUNG JABUNG TIMUR',
                                'KAB. TEBO',
                                'KOTA JAMBI',
                                'KOTA SUNGAIPENUH',
                                ),
                        'JAWA BARAT' => array(
                                'KAB. BANDUNG',
                                'KAB. BANDUNG BARAT',
                                'KAB. BEKASI',
                                'KAB. BOGOR',
                                'KAB. CIAMIS',
                                'KAB. CIANJUR',
                                'KAB. CIREBON',
                                'KAB. GARUT',
                                'KAB. INDRAMAYU',
                                'KAB. KARAWANG',
                                'KAB. KUNINGAN',
                                'KAB. MAJALENGKA',
                                'KAB. PANGANDARAN',
                                'KAB. PURWAKARTA',
                                'KAB. SUBANG',
                                'KAB. SUKABUMI',
                                'KAB. SUMEDANG',
                                'KAB. TASIKMALAYA',
                                'KOTA BANDUNG',
                                'KOTA BANJAR',
                                'KOTA BEKASI',
                                'KOTA BOGOR',
                                'KOTA CIMAHI',
                                'KOTA CIREBON',
                                'KOTA DEPOK',
                                'KOTA SUKABUMI',
                                'KOTA TASIKMALAYA',
                                ),
                        'JAWA TENGAH' => array(
                                'KAB. BANJARNEGARA',
                                'KAB. BANYUMAS',
                                'KAB. BATANG',
                                'KAB. BLORA',
                                'KAB. BOYOLALI',
                                'KAB. BREBES',
                                'KAB. CILACAP',
                                'KAB. DEMAK',
                                'KAB. GROBOGAN',
                                'KAB. JEPARA',
                                'KAB. KARANGANYAR',
                                'KAB. KEBUMEN',
                                'KAB. KENDAL',
                                'KAB. KLATEN',
                                'KAB. KUDUS',
                                'KAB. MAGELANG',
                                'KAB. PATI',
                                'KAB. PEKALONGAN',
                                'KAB. PEMALANG',
                                'KAB. PURBALINGGA',
                                'KAB. PURWOREJO',
                                'KAB. REMBANG',
                                'KAB. SEMARANG',
                                'KAB. SRAGEN',
                                'KAB. SUKOHARJO',
                                'KAB. TEGAL',
                                'KAB. TEMANGGUNG',
                                'KAB. WONOGIRI',
                                'KAB. WONOSOBO',
                                'KOTA MAGELANG',
                                'KOTA PEKALONGAN',
                                'KOTA SALATIGA',
                                'KOTA SEMARANG',
                                'KOTA SURAKARTA (SOLO)',
                                'KOTA TEGAL',
                                ),
                        'JAWA TIMUR' => array(
                                'KAB. BANGKALAN',
                                'KAB. BANYUWANGI',
                                'KAB. BLITAR',
                                'KAB. BOJONEGORO',
                                'KAB. BONDOWOSO',
                                'KAB. GRESIK',
                                'KAB. JEMBER',
                                'KAB. JOMBANG',
                                'KAB. KEDIRI',
                                'KAB. LAMONGAN',
                                'KAB. LUMAJANG',
                                'KAB. MADIUN',
                                'KAB. MAGETAN',
                                'KAB. MALANG',
                                'KAB. MOJOKERTO',
                                'KAB. NGANJUK',
                                'KAB. NGAWI',
                                'KAB. PACITAN',
                                'KAB. PAMEKASAN',
                                'KAB. PASURUAN',
                                'KAB. PONOROGO',
                                'KAB. PROBOLINGGO',
                                'KAB. SAMPANG',
                                'KAB. SIDOARJO',
                                'KAB. SITUBONDO',
                                'KAB. SUMENEP',
                                'KAB. TRENGGALEK',
                                'KAB. TUBAN',
                                'KAB. TULUNGAGUNG',
                                'KOTA BATU',
                                'KOTA BLITAR',
                                'KOTA KEDIRI',
                                'KOTA MADIUN',
                                'KOTA MALANG',
                                'KOTA MOJOKERTO',
                                'KOTA PASURUAN',
                                'KOTA PROBOLINGGO',
                                'KOTA SURABAYA',
                                ),
                        'KALIMANTAN BARAT' => array(
                                'KAB. BENGKAYANG',
                                'KAB. KAPUAS HULU',
                                'KAB. KAYONG UTARA',
                                'KAB. KETAPANG',
                                'KAB. KUBU RAYA',
                                'KAB. LANDAK',
                                'KAB. MELAWI',
                                'KAB. PONTIANAK',
                                'KAB. SAMBAS',
                                'KAB. SANGGAU',
                                'KAB. SEKADAU',
                                'KAB. SINTANG',
                                'KOTA PONTIANAK',
                                'KOTA SINGKAWANG',
                                ),
                        'KALIMANTAN SELATAN' => array(
                                'KAB. BALANGAN',
                                'KAB. BANJAR',
                                'KAB. BARITO KUALA',
                                'KAB. HULU SUNGAI SELATAN',
                                'KAB. HULU SUNGAI TENGAH',
                                'KAB. HULU SUNGAI UTARA',
                                'KAB. KOTA BARU',
                                'KAB. TABALONG',
                                'KAB. TANAH BUMBU',
                                'KAB. TANAH LAUT',
                                'KAB. TAPIN',
                                'KOTA BANJARBARU',
                                'KOTA BANJARMASIN',
                                ),
                        'KALIMANTAN TENGAH' => array(
                                'KAB. BARITO SELATAN',
                                'KAB. BARITO TIMUR',
                                'KAB. BARITO UTARA',
                                'KAB. GUNUNG MAS',
                                'KAB. KAPUAS',
                                'KAB. KATINGAN',
                                'KAB. KOTA WARINGIN BARAT',
                                'KAB. KOTA WARINGIN TIMUR',
                                'KAB. LAMANDAU',
                                'KAB. MURUNG RAYA',
                                'KAB. PULANG PISAU',
                                'KAB. SUKAMARA',
                                'KAB. SERUYAN',
                                'KOTA PALANGKA RAYA',
                                ),
                        'KALIMANTAN TIMUR' => array(
                                'KAB. BERAU',
                                'KAB. KUTAI BARAT',
                                'KAB. KUTAI KARTANEGARA',
                                'KAB. KUTAI TIMUR',
                                'KAB. PASER',
                                'KAB. PENAJAM PASER UTARA',
                                'KAB. MAHAKAM ULU',
                                'KOTA BALIKPAPAN',
                                'KOTA BONTANG',
                                'KOTA SAMARINDA',
                                ),
                        'KALIMANTAN UTARA' => array(
                                'KAB. BULUNGAN',
                                'KAB. MALINAU',
                                'KAB. NUNUKAN',
                                'KAB. TANA TIDUNG',
                                'KOTA TARAKAN',
                                ),
                        'KEPULAUAN RIAU' => array(
                                'KAB. BINTAN',
                                'KAB. KARIMUN',
                                'KAB. KEPULAUAN ANAMBAS',
                                'KAB. LINGGA',
                                'KAB. NATUNA',
                                'KOTA BATAM',
                                'KOTA TANJUNG PINANG',
                                ),
                        'LAMPUNG' => array(
                                'KAB. LAMPUNG BARAT',
                                'KAB. LAMPUNG SELATAN',
                                'KAB. LAMPUNG TENGAH',
                                'KAB. LAMPUNG TIMUR',
                                'KAB. LAMPUNG UTARA',
                                'KAB. MESUJI',
                                'KAB. PESAWARAN',
                                'KAB. PRINGSEWU',
                                'KAB. TANGGAMUS',
                                'KAB. TULANG BAWANG',
                                'KAB. TULANG BAWANG BARAT',
                                'KAB. WAY KANAN',
                                'KAB. PESISIR BARAT',
                                'KOTA BANDAR LAMPUNG',
                                'KOTA KOTABUMI',
                                'KOTA LIWA',
                                'KOTA METRO',
                                ),
                        'MALUKU' => array(
                                'KAB. BURU',
                                'KAB. BURU SELATAN',
                                'KAB. KEPULAUAN ARU',
                                'KAB. MALUKU BARAT DAYA',
                                'KAB. MALUKU TENGAH',
                                'KAB. MALUKU TENGGARA',
                                'KAB. MALUKU TENGGARA BARAT',
                                'KAB. SERAM BAGIAN BARAT',
                                'KAB. SERAM BAGIAN TIMUR',
                                'KOTA AMBON',
                                'KOTA TUAL',
                                ),
                        'MALUKU UTARA' => array(
                                'KAB. HALMAHERA BARAT',
                                'KAB. HALMAHERA TENGAH',
                                'KAB. HALMAHERA UTARA',
                                'KAB. HALMAHERA SELATAN',
                                'KAB. HALMAHERA TIMUR',
                                'KAB. KEPULAUAN SULA',
                                'KAB. PULAU MOROTAI',
                                'KAB. PULAU TALIABU',
                                'KOTA TERNATE',
                                'KOTA TIDORE KEPULAUAN',
                                ),
                        'NUSA TENGGARA BARAT (NTB)' => array(
                                'KAB. BIMA',
                                'KAB. DOMPU',
                                'KAB. LOMBOK BARAT',
                                'KAB. LOMBOK TENGAH',
                                'KAB. LOMBOK TIMUR',
                                'KAB. LOMBOK UTARA',
                                'KAB. SUMBAWA',
                                'KAB. SUMBAWA BARAT',
                                'KOTA BIMA',
                                'KOTA MATARAM',
                                ),
                        'NUSA TENGGARA TIMUR (NTT)' => array(
                                'KAB. ALOR',
                                'KAB. BELU',
                                'KAB. ENDE',
                                'KAB. FLORES TIMUR',
                                'KAB. KUPANG',
                                'KAB. LEMBATA',
                                'KAB. MANGGARAI',
                                'KAB. MANGGARAI BARAT',
                                'KAB. MANGGARAI TIMUR',
                                'KAB. NGADA',
                                'KAB. NAGEKEO',
                                'KAB. ROTE NDAO',
                                'KAB. SABU RAIJUA',
                                'KAB. SIKKA',
                                'KAB. SUMBA BARAT',
                                'KAB. SUMBA BARAT DAYA',
                                'KAB. SUMBA TENGAH',
                                'KAB. SUMBA TIMUR',
                                'KAB. TIMOR TENGAH SELATAN',
                                'KAB. TIMOR TENGAH UTARA',
                                'KOTA KUPANG',
                                ),
                        'PAPUA' => array(
                                'KAB. ASMAT',
                                'KAB. BIAK NUMFOR',
                                'KAB. BOVEN DIGOEL',
                                'KAB. DEIYAI',
                                'KAB. DOGIYAI',
                                'KAB. INTAN JAYA',
                                'KAB. JAYAPURA',
                                'KAB. JAYAWIJAYA',
                                'KAB. KEEROM',
                                'KAB. KEPULAUAN YAPEN',
                                'KAB. LANNY JAYA',
                                'KAB. MAMBERAMO RAYA',
                                'KAB. MAMBERAMO TENGAH',
                                'KAB. MAPPI',
                                'KAB. MERAUKE',
                                'KAB. MIMIKA',
                                'KAB. NABIRE',
                                'KAB. NDUGA',
                                'KAB. PANIAI',
                                'KAB. PEGUNUNGAN BINTANG',
                                'KAB. PUNCAK',
                                'KAB. PUNCAK JAYA',
                                'KAB. SARMI',
                                'KAB. SUPIORI',
                                'KAB. TOLIKARA',
                                'KAB. WAROPEN',
                                'KAB. YAHUKIMO',
                                'KAB. YALIMO',
                                'KOTA JAYAPURA',
                                ),
                        'PAPUA BARAT' => array(
                                'KAB. FAKFAK',
                                'KAB. KAIMANA',
                                'KAB. MANOKWARI',
                                'KAB. MANOKWARI SELATAN',
                                'KAB. MAYBRAT',
                                'KAB. PEGUNUNGAN ARFAK',
                                'KAB. RAJA AMPAT',
                                'KAB. SORONG',
                                'KAB. SORONG SELATAN',
                                'KAB. TAMBRAUW',
                                'KAB. TELUK BINTUNI',
                                'KAB. TELUK WONDAMA',
                                'KOTA SORONG',
                                ),
                        'RIAU' => array(
                                'KAB. BENGKALIS',
                                'KAB. INDRAGIRI HILIR',
                                'KAB. INDRAGIRI HULU',
                                'KAB. KAMPAR',
                                'KAB. KUANTAN SINGINGI',
                                'KAB. PELALAWAN',
                                'KAB. ROKAN HILIR',
                                'KAB. ROKAN HULU',
                                'KAB. SIAK',
                                'KAB. KEPULAUAN MERANTI',
                                'KOTA DUMAI',
                                'KOTA PEKANBARU',
                                ),
                        'SULAWESI BARAT' => array(
                                'KAB. MAJENE',
                                'KAB. MAMASA',
                                'KAB. MAMUJU',
                                'KAB. MAMUJU UTARA',
                                'KAB. POLEWALI MANDAR',
                                'KAB. MAMUJU TENGAH',
                                ),
                        'SULAWESI SELATAN' => array(
                                'KAB. BANTAENG',
                                'KAB. BARRU',
                                'KAB. BONE WATAMPONE',
                                'KAB. BULUKUMBA',
                                'KAB. ENREKANG',
                                'KAB. GOWA',
                                'KAB. JENEPONTO',
                                'KAB. KEPULAUAN SELAYAR',
                                'KAB. LUWU',
                                'KAB. LUWU TIMUR',
                                'KAB. LUWU UTARA',
                                'KAB. MAROS',
                                'KAB. PANGKAJENE DAN KEPULAUAN',
                                'KAB. SELAYAR (KEPULAUAN SELAYAR)',
                                'KAB. PINRANG',
                                'KAB. SIDENRENG RAPPANG/RAPANG',
                                'KAB. SINJAI',
                                'KAB. SOPPENG',
                                'KAB. TAKALAR',
                                'KAB. TANA TORAJA',
                                'KAB. TORAJA UTARA',
                                'KAB. WAJO',
                                'KOTA MAKASSAR',
                                'KOTA PALOPO',
                                'KOTA PAREPARE',
                                ),
                        'SULAWESI TENGAH' => array(
                                'KAB. BANGGAI',
                                'KAB. BANGGAI KEPULAUAN',
                                'KAB. BANGGAI LAUT',
                                'KAB. BUOL',
                                'KAB. DONGGALA',
                                'KAB. MOROWALI',
                                'KAB. PARIGI MOUTONG',
                                'KAB. POSO',
                                'KAB. SIGI',
                                'KAB. TOJO UNA-UNA',
                                'KAB. TOLITOLI',
                                'KOTA PALU',
                                ),
                        'SULAWESI TENGGARA' => array(
                                'KAB. BOMBANA',
                                'KAB. BUTON',
                                'KAB. BUTON UTARA',
                                'KAB. KOLAKA',
                                'KAB. KOLAKA TIMUR',
                                'KAB. KOLAKA UTARA',
                                'KAB. KONAWE',
                                'KAB. KONAWE SELATAN',
                                'KAB. KONAWE UTARA',
                                'KAB. KONAWE KEPULAUAN',
                                'KAB. MUNA',
                                'KAB. WAKATOBI',
                                'KOTA BAU-BAU',
                                'KOTA KENDARI',
                                ),
                        'SULAWESI UTARA' => array(
                                'KAB. BOLAANG MONGONDOW',
                                'KAB. BOLAANG MONGONDOW SELATAN',
                                'KAB. BOLAANG MONGONDOW TIMUR',
                                'KAB. BOLAANG MONGONDOW UTARA',
                                'KAB. KEPULAUAN SANGIHE',
                                'KAB. KEPULAUAN SIAU TAGULANDANG BIARO',
                                'KAB. KEPULAUAN TALAUD',
                                'KAB. MINAHASA',
                                'KAB. MINAHASA SELATAN',
                                'KAB. MINAHASA TENGGARA',
                                'KAB. MINAHASA UTARA',
                                'KOTA BITUNG',
                                'KOTA KOTAMOBAGU',
                                'KOTA MANADO',
                                'KOTA TOMOHON',
                                ),
                        'SUMATERA BARAT' => array(
                                'KAB. AGAM',
                                'KAB. DHARMASRAYA',
                                'KAB. KEPULAUAN MENTAWAI',
                                'KAB. LIMA PULUH KOTO/KOTA',
                                'KAB. PADANG PARIAMAN',
                                'KAB. PASAMAN',
                                'KAB. PASAMAN BARAT',
                                'KAB. PESISIR SELATAN',
                                'KAB. SIJUNJUNG',
                                'KAB. SOLOK',
                                'KAB. SOLOK SELATAN',
                                'KAB. TANAH DATAR',
                                'KOTA BUKITTINGGI',
                                'KOTA PADANG',
                                'KOTA PADANG PANJANG',
                                'KOTA PARIAMAN',
                                'KOTA PAYAKUMBUH',
                                'KOTA SAWAH LUNTO',
                                'KOTA SOLOK',
                                ),
                        'SUMATERA SELATAN' => array(
                                'KAB. BANYUASIN',
                                'KAB. EMPAT LAWANG',
                                'KAB. LAHAT',
                                'KAB. MUARA ENIM',
                                'KAB. MUSI BANYUASIN',
                                'KAB. MUSI RAWAS',
                                'KAB. OGAN ILIR',
                                'KAB. OGAN KOMERING ILIR',
                                'KAB. OGAN KOMERING ULU',
                                'KAB. OGAN KOMERING ULU SELATAN',
                                'KAB. PENUKAL ABAB LEMATANG ILIR',
                                'KAB. OGAN KOMERING ULU TIMUR',
                                'KOTA LUBUK LINGGAU',
                                'KOTA PAGAR ALAM',
                                'KOTA PALEMBANG',
                                'KOTA PRABUMULIH',
                                ),
                        'SUMATERA UTARA' => array(
                                'KAB. ASAHAN',
                                'KAB. BATUBARA',
                                'KAB. DAIRI',
                                'KAB. DELI SERDANG',
                                'KAB. HUMBANG HASUNDUTAN',
                                'KAB. KARO',
                                'KAB. KARO KABANJAHE',
                                'KAB. LABUHAN BATU',
                                'KAB. LABUHAN BATU SELATAN',
                                'KAB. LABUHAN BATU UTARA',
                                'KAB. LANGKAT',
                                'KAB. MANDAILING NATAL',
                                'KAB. NIAS',
                                'KAB. NIAS BARAT',
                                'KAB. NIAS SELATAN',
                                'KAB. NIAS UTARA',
                                'KAB. PADANG LAWAS',
                                'KAB. PADANG LAWAS UTARA',
                                'KAB. PAKPAK BHARAT',
                                'KAB. SAMOSIR',
                                'KAB. SERDANG BEDAGAI',
                                'KAB. SIMALUNGUN',
                                'KAB. TAPANULI SELATAN',
                                'KAB. TAPANULI TENGAH',
                                'KAB. TAPANULI UTARA',
                                'KAB. TOBA SAMOSIR',
                                'KOTA BINJAI',
                                'KOTA GUNUNGSITOLI',
                                'KOTA MEDAN',
                                'KOTA PADANG SIDEMPUAN',
                                'KOTA PEMATANG SIANTAR',
                                'KOTA SIBOLGA',
                                'KOTA TANJUNG BALAI',
                                'KOTA TEBING TINGGI',
                                ),
                        );
                
                return $kabupaten[$value];
        }